<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bigine</string>
		<string>bws</string>
	</array>
	<key>name</key>
	<string>Bigine</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#bigine</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>action</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#action-choose</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-mxximum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-arithmetic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-state</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-director</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-words</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-def-data</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-def-coll</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-coll-pop</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-coll-append</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-pause</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-camera-set</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-camera-reset</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-camera-zoom</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-camera-move</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-camera-shake</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#action-curtains</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>action-arithmetic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\t+)(数据合值)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.bigine.literal meta.bigine.ref.state.perline</string>
					<key>end</key>
					<string>^(?!\1\t)</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#state-per-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\t+)(数据差值)(?:（([^，\s]+)，([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.bigine.literal meta.bigine.ref.state.perline</string>
					<key>end</key>
					<string>^(?!\1\t)</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket meta.bigine.ref.state.comma meta.bigine.after.comma</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#state-per-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>action-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\t+)(?:(且|或|那么|否则|循环)|(如果)(?:（([^，\s](?:|[^，]*[^，\s]))）|(（.*）)))：?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!\1\t)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\t+)(如果数据)(?:（([^，\s]+)）|(（.*）))：?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?!\1\t)</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>action-camera-move</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(移动镜头)(?:(?:|(（）)|（(?:([快中慢])|([^）]*))）)(?:：(左上|上|右上|左|中|右|左下|下|右下)|(：.*))|(：.*))$\n?</string>
		</dict>
		<key>action-camera-reset</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(复位镜头)(?:(?:|(（）)|（(?:([快中慢])|([^）]*))）)：?|(.*))$\n?</string>
		</dict>
		<key>action-camera-set</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(设置镜头)(?:(?:：(左上|上|右上|左|中|右|左下|下|右下)|(：.*))|(：.*))$\n?</string>
		</dict>
		<key>action-camera-shake</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(抖动镜头)$\n?</string>
		</dict>
		<key>action-camera-zoom</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(放大镜头)(?:(?:|(（）)|（(?:([快中慢])|([^）]*))）)(?:：(左上|上|右上|左|中|右|左下|下|右下)|(：.*))|(：.*))$\n?</string>
		</dict>
		<key>action-choose</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\t+)(选择)(?:|（([^，\s]+)）|(（.*）))(?:|：(\S+)|(：.*))$\n?</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.other.choose.bigine</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.bigine.literal</string>
					<key>end</key>
					<string>^(?!\1\t)</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket meta.bigine.ref.choose.colon meta.bigine.after.colon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#option-per-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(\t+)(定义选择)(?:：(\S+)|(：.*))$\n?</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.choose.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.bigine.literal</string>
					<key>end</key>
					<string>^(?!\1\t)</string>
					<key>name</key>
					<string>meta.bigine.ref.choose.colon meta.bigine.after.colon</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#option-per-line</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.choose.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(添加选项)(?:（([^，\s]+)，([^，\s]+)(?:|，([1-9]\d*))）|(（.*）))(?:|：(.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.choose.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.choose.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(去除选项)(?:（([^，\s]+)，([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.choose.bracket meta.bigine.after.bracket</string>
				</dict>
			</array>
		</dict>
		<key>action-coll-append</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.variable.bigine</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\t\t)(增加元素)(?:(?:(（）)|（(\S+)）)(?:(?:：(\S+))|(：))|(：.*))$\n?</string>
		</dict>
		<key>action-coll-pop</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.variable.bigine</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\t\t)(删除元素)(?:(?:(（）)|（(\S+)）)(?:(?:：(\S+))|(：))|(：.*))$\n?</string>
		</dict>
		<key>action-curtains</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(切幕动画)(?:(?:|(（）)|（(?:(淡入淡出|水平百叶窗|垂直百叶窗)|([^）]*))）)：?|(.*))?$\n?</string>
		</dict>
		<key>action-def-coll</key>
		<dict>
			<key>begin</key>
			<string>^(\t\t)(定义集合)(?:(?:(（）)|（(\S+)）)(?:(?:：(\S+))|(：))|(：.*))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.variable.bigine</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.bigine.literal meta.bigine.ref.state.perline</string>
			<key>end</key>
			<string>^(?!\1\t+)</string>
			<key>name</key>
			<string>meta.bigine.ref.struct.bracket meta.bigine.after.bracket</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#def-coll-per-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>action-def-data</key>
		<dict>
			<key>begin</key>
			<string>^(\t\t)(定义数据)(?:(?:(（）)|（(\S+)）)(?:(?:：(\S+))|(：))|(：.*))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.variable.bigine</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.bigine.literal meta.bigine.ref.state.perline</string>
			<key>end</key>
			<string>^(?!\1\t+)</string>
			<key>name</key>
			<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#def-data-per-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>action-director</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bigine</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(设置人物|人物出场)(?:|（(最左|左|左中|中|右中|右|最右)）|(（.*）))(?:：([^，\s](?:|[^，]*[^，\s]))(?:|，([^，\s]+))|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.char.colon meta.bigine.after.colon meta.bigine.ref.pose.comma meta.bigine.after.comma</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(人物离场)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.char.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(播放音乐)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.bgm.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(播放音效)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.se.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(展示特写)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.cg.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+((?:设置|进入)房间)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.room.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(设置时间)(?:（([^，\s]+)）|(（.*）))：?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(改变神态)(?:（([^，\s]+)）|(（.*）))(?:：([^，\s]+)|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.char.bracket meta.bigine.after.bracket meta.bigine.ref.pose.colon meta.bigine.after.colon</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(评分)(?:（(传奇|超绝|完美|优秀|及格)(?:|，([^，\s]+)|(，.*))）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.state.comma meta.bigine.after.comma</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(关闭特写|移动中止|停止音乐)：?$\n?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(人物移动)(?:（([^，\s]+)）|(（.*）))(?:：(最左|左|左中|中|右中|右|最右)|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.char.bracket meta.bigine.after.bracket</string>
				</dict>
			</array>
		</dict>
		<key>action-mxximum</key>
		<dict>
			<key>begin</key>
			<string>^(\t+)(最[大小]数据)(?:|（([^，\s]+)）|(（.*）))：?$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.state.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.bigine.literal meta.bigine.ref.state.perline</string>
			<key>end</key>
			<string>^(?!\1\t)</string>
			<key>name</key>
			<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#state-per-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>action-pause</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(停顿)(?:(?:|(（）)|（(?:([短中长])|([^）]*))）)：?|(.*))$\n?</string>
		</dict>
		<key>action-state</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(当数据)(?:（([^，\s]+?)，([^，\s](?:|[^，]*[^，\s]))(?:|，(不?[等大小]于))）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+((?:对比|随机)数据)(?:（([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+((?:设置|增加)数据)(?:（([^，\s]+)）|(（.*）))(?:：(\S(?:|.*\S))|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.state.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(复制数据)(?:（([^，\s]+)，([^，\s]+)）|(（.*）))：?$\n?</string>
					<key>name</key>
					<string>meta.bigine.ref.state.bracket meta.bigine.after.bracket meta.bigine.ref.state.comma meta.bigine.after.comma</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(当时间)(?:（([^，\s]+)）|(（.*）))：?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(自动存档)(?:|（([^，\s]+)）|(（.*）))：?$\n?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(游戏(?:完结|失败)|循环中止)：?$\n?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(打赏)(?:（([1-9]\d*)）|(（.*）))：?$\n?</string>
				</dict>
			</array>
		</dict>
		<key>action-words</key>
		<dict>
			<key>begin</key>
			<string>^\t+(?:([旁独]白|提示)(?=：)|(对白)(?=（))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=对白)(?:（([^，\s]+)，([^，\s]+)(?:|，(\S(?:|.*?\S)))）|(（.*）))(?=：)</string>
					<key>name</key>
					<string>meta.bigine.ref.char.bracket meta.bigine.after.bracket meta.bigine.ref.char.comma meta.bigine.after.comma</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=：)</string>
					<key>contentName</key>
					<string>string.quoted.double.bigine</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>【(.+?)】</string>
							<key>name</key>
							<string>string.regexp.bigine</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.state.bigine</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.other.state.bigine</string>
								</dict>
							</dict>
							<key>match</key>
							<string>〈(\S+?)〉|＜(\S+?)＞</string>
							<key>name</key>
							<string>string.interpolated.bigine</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>bigine</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scene</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct</string>
				</dict>
			</array>
		</dict>
		<key>def-coll-per-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t\t\t(\S+)$\n?</string>
		</dict>
		<key>def-data-per-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.data.def.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t\t\t(\S+)：(\S+)$\n?</string>
		</dict>
		<key>empty-field-per-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t(空)$</string>
		</dict>
		<key>field-per-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.state.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t(\S+)(?:：(\S+)|(：))$</string>
		</dict>
		<key>id-per-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t\t(?:(\S+)|(.*))(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$</string>
		</dict>
		<key>illegal</key>
		<dict>
			<key>match</key>
			<string>^.*$</string>
			<key>name</key>
			<string>invalid.illegal.bigine</string>
		</dict>
		<key>option-per-line</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(?:([^（）\s]+?)(?:|（([1-9]\d*)）)|(.*))(?:：(\S(?:|.*\S))|(：.*))$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.character.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t+(\S(?:|.*\S))$</string>
				</dict>
			</array>
		</dict>
		<key>scene</key>
		<dict>
			<key>begin</key>
			<string>^(事件)(?:：(\S+)|(：.*))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.scene</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>scene type</string>
					<key>match</key>
					<string>^\t(类型)：(?:((?:开始|完结|失败)时|(?:进入|离开)（([^，\s]+?)）(?:前|后))|(.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.scene.type meta.bigine.ref.room.bracket meta.bigine.after.bracket</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\t(条件)：?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>scene conditions</string>
					<key>end</key>
					<string>^(?=$|\t?\S)</string>
					<key>name</key>
					<string>meta.bigine.scene.conditions</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\t(内容)：?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>scene content</string>
					<key>end</key>
					<string>^(?=$|\t?\S)</string>
					<key>name</key>
					<string>meta.bigine.scene.content</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#action</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>state-per-line</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.state.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\t+(\S+)$\n?</string>
		</dict>
		<key>struct</key>
		<dict>
			<key>begin</key>
			<string>^(?=$|\S)</string>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct-resource</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-theme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-autoplay</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-player</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-character</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-room</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-map</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-sound</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-cg</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-status</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-structure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-panel</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-autoplay</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(自动播放)(?:|：(.*))$\n?</string>
			<key>name</key>
			<string>meta.bigine.autoplay</string>
		</dict>
		<key>struct-cg</key>
		<dict>
			<key>begin</key>
			<string>^(特写)(?:：(\S+)|(：.*))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.cg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t(画面)(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.cg.source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-character</key>
		<dict>
			<key>begin</key>
			<string>^(人物)(?:|（([^，\s]+)）|(（.*）))(?:：(\S+)|(：.*))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.char</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t(头像)(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.char.avatar</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\t(姿态)：?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=$|\t?\S)</string>
					<key>name</key>
					<string>meta.bigine.char.poses</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#id-per-line</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-map</key>
		<dict>
			<key>begin</key>
			<string>^(地图)(?:|（([^，\s]+)）|(（.*）))(?:：(\S+)|(：.*))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.map</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t(底图)(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.map.back</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\t(交互点)(?:|（([^，\s]+)）|(（.*）))(?:：(\S+)|(：.*))$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bigine</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=$|\t?\S)</string>
					<key>name</key>
					<string>meta.bigine.map.point</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.bigine</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.language.bigine</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.bigine</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^\t\t(高亮)(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$\n?</string>
							<key>name</key>
							<string>meta.bigine.map.point.cover</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.bigine</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.other.inherited-class.bigine</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.bigine</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^\t\t(对应房间)(?:：(\S+)|(：.*))$\n?</string>
							<key>name</key>
							<string>meta.bigine.map.point.link</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>storage.modifier.bigine</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.bigine</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.bigine</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.bigine</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.bigine</string>
								</dict>
								<key>6</key>
								<dict>
									<key>name</key>
									<string>constant.numeric.bigine</string>
								</dict>
								<key>7</key>
								<dict>
									<key>name</key>
									<string>invalid.illegal.bigine</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^\t\t(区域)(?:：(-?\d+)，(-?\d+)，(-?\d+)，(-?\d+)(?:|，(\d+))|(：.*))$\n?</string>
							<key>name</key>
							<string>meta.bigine.map.point.region</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#illegal</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-panel</key>
		<dict>
			<key>begin</key>
			<string>^(面板)：$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.panel</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct-panel-simple</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#struct-panel-coll</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-panel-coll</key>
		<dict>
			<key>begin</key>
			<string>^\t(集合面板)(：(\S+))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.panel.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\t\t+)</string>
			<key>name</key>
			<string>meta.bigine.panel.coll</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.variable.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>collection name defined</string>
					<key>match</key>
					<string>^\t\t(使用集合)(：(\S+))$\n?</string>
					<key>name</key>
					<string>meta.bigine.panel.coll.name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>collection structure defined</string>
					<key>match</key>
					<string>^\t\t(集合结构)(：(\S+))$\n?</string>
					<key>name</key>
					<string>meta.bigine.panel.coll.structure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-panel-simple</key>
		<dict>
			<key>begin</key>
			<string>^\t(简单面板)(：(\S+))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.panel.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\t\t+)</string>
			<key>name</key>
			<string>meta.bigine.panel.simple</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct-panel-simple-item</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-panel-simple-item</key>
		<dict>
			<key>begin</key>
			<string>^\t\t(条目)(：(\S+))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structure.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\t\t\t+)</string>
			<key>name</key>
			<string>meta.bigine.panel.simple.item</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.structure.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>real variable name</string>
					<key>match</key>
					<string>^\t\t\t(数据名)(：(\S+))$\n?</string>
					<key>name</key>
					<string>meta.bigine.panel.simple.item.name</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>display type</string>
					<key>match</key>
					<string>^\t\t\t(数据类别)(：(星|心))$\n?</string>
					<key>name</key>
					<string>meta.bigine.panel.simple.item.type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-player</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(主角)(?:：(\S+)|(：.*))$\n?</string>
			<key>name</key>
			<string>meta.bigine.player</string>
		</dict>
		<key>struct-resource</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(素材包)(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$\n?</string>
			<key>name</key>
			<string>meta.bigine.suite meta.bigine.after.colon</string>
		</dict>
		<key>struct-room</key>
		<dict>
			<key>begin</key>
			<string>^(房间)(?:|（([^，\s]+)）|(（.*）))(?:：(\S+)|(：.*))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.other.inherited-class.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.bigine</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.room</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t(使用地图)(?:：(\S+)|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.room.map</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\t(时刻)：?$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(?=$|\t?\S)</string>
					<key>name</key>
					<string>meta.bigine.char.snaps</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#id-per-line</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-sound</key>
		<dict>
			<key>begin</key>
			<string>^(音乐|音效)(?:：(\S+)|(：.*))$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.sound</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.modifier.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.bigine</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\t(音源)(?:：(\h{8}-\h{4}-\h{4}-\h{4}-\h{12})|(：.*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.sound.source</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-status</key>
		<dict>
			<key>begin</key>
			<string>^(状态)(?:|：|：(\S+))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>meta.bigine.literal meta.bigine.ref.state.perline meta.bigine.ref.state.colon meta.bigine.after.colon</string>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.status</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#field-per-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#empty-field-per-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#state-per-line</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-structure</key>
		<dict>
			<key>begin</key>
			<string>^(结构)(：(\S+))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=$|\S)</string>
			<key>name</key>
			<string>meta.bigine.structure</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#struct-structure-field</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-structure-field</key>
		<dict>
			<key>begin</key>
			<string>^\t(字段)(：(\S+))$\n?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.structure.bigine</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\t\t+)</string>
			<key>name</key>
			<string>meta.bigine.structure.field</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.inherited-class.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>structure field type</string>
					<key>match</key>
					<string>^\t\t(类别)(：(名称|人物|房间|特写|星|心))$\n?</string>
					<key>name</key>
					<string>meta.bigine.structure.field.type</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.bigine</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bigine</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>structure field limit</string>
					<key>match</key>
					<string>^\t\t(上限)(：([1-9][0-9]*))$\n?</string>
					<key>name</key>
					<string>meta.bigine.structure.field.limit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#illegal</string>
				</dict>
			</array>
		</dict>
		<key>struct-theme</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.bigine</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.bigine</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.bigine</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(主题)(?:：(\S+)|(：.*))$\n?</string>
			<key>name</key>
			<string>meta.bigine.theme meta.bigine.after.colon</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.bigine</string>
	<key>uuid</key>
	<string>74ffd726-943b-4531-8657-cebb5215f277</string>
</dict>
</plist>
